### ISSUE TITLE
Login stalls when running instance installed on web server

### ISSUE THREAD

**Issue by NateEaton** [lurume84/bling-viewer#4]
I had assumed I could install it in the webserver on my Synology NAS. It runs, i.e., the login dialog comes up and I can interact with it, but once I select Login, it looks like it is doing something but the dialog never clears, it appears I’m not actually logged in.

Is this still a CORS issue? Is it going to take starting Chrome instance with the disable web security flag? I had tried the approach from Mac using that but got an error that I was using an obsolete flag.

**Comment by lurume84** [comment]
I confirm it's because of CORS. Chrome does no longer allow to use the disable-web-security command line because of security issues involved. I have a chrome version compiled by myself without this limitation and application works. Typical CORS plugin for Chrome does not work with Blink Servers. 

You have several options ahead:

- Use a reverse proxy: there is a bling-proxy.pl file in the root folder to create a reverse proxy using perl, if you open index.html and put http://localhost:3000/ in ajaxprefilter line, inside "". If you need more details I can add how to do it to documentation.
- Use a custom browser like I did, you can get one from cefbuilds site. I can also give you advice.
- Use your webserver as proxy. This is more complicated but if you point calls from blink servers in *interactor.js files to your own server, you will be able to proxy calls to the blink servers from php or whatever language you have.
